import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    dashboard: 'Dashboard',
    applications: 'Applications',
    meritList: 'Merit List',
    cutoffPrediction: 'Cut-off Prediction',
    seatAllocation: 'Seat Allocation',
    payments: 'Payments',
    exams: 'Entrance Exams',
    mockTests: 'Mock Tests',
    documents: 'Document Center',
    settings: 'Settings',
    logout: 'Logout',
    engineeringAdmissionsPortal: 'Engineering Admissions Portal',
    searchPrograms: 'Search engineering programs...',
    notifications: 'Notifications',
    studentProfile: 'Student Profile',
    editSettings: 'Edit Account Settings',
    myApplications: 'My Applications',
    logoutSession: 'Logout / Session Reset',
    recentApplications: 'Recent Engineering Applications',
    startApplication: 'Start New Engineering Application',
    draftApplication: 'Draft Engineering Application',
    cancel: 'Cancel',
    submit: 'Submit Application',
    studentName: 'Student Name',
    email: 'Email',
    program: 'Engineering Program',
    department: 'Department',
    class12Marks: 'Class 12 Marks (%)',
    jeeComedkScore: 'JEE/COMEDK Score (%)',
    coursePreferences: 'Course Preferences (Optional)',
    addPreference: '+ Add Preference',
    applicationId: 'Application ID',
    academicMarks: 'Academic Marks',
    examScore: 'Exam Score',
    totalScore: 'Total Score',
    paymentStatus: 'Payment Status',
    status: 'Status',
    actions: 'Actions',
    view: 'View',
    pay: 'Pay',
    paid: 'Paid',
    pending: 'Pending',
    failed: 'Failed',
    underReview: 'Under Review',
    admitted: 'Admitted',
    processing: 'Processing',
    jeeQualified: 'JEE Qualified',
    // Rural features
    ruralSupport: 'Rural Support',
    scholarships: 'Scholarships',
    helplines: 'Helplines',
    coachingCenters: 'Coaching Centers',
    transportation: 'Transportation Guide',
    communityForum: 'Community Forum',
    computerLiteracy: 'Computer Literacy',
    offlineForms: 'Offline Forms',
    downloadForm: 'Download Application Form',
    smsNotifications: 'SMS Notifications',
    language: 'Language',
    english: 'English',
    hindi: 'हिंदी',
    selectLanguage: 'Select Language',
    ruralFriendlyMode: 'Rural Friendly Mode',
    largeText: 'Large Text',
    voiceGuidance: 'Voice Guidance',
    // New features
    applyJee: 'Apply for JEE Main',
    applyComedk: 'Apply for COMEDK',
    gatewayToPrograms: 'Your gateway to top engineering programs through JEE Main and COMEDK',
    applyForPrograms: 'Apply for engineering programs through JEE Main and COMEDK',
    engineeringApplications: 'Engineering Applications',
    upcomingExams: 'Upcoming Exams',
    jeeRegistrationClosing: 'JEE Main registration is closing soon!',
    applicationUnderReview: 'Your engineering application is Under Review.',
    systemMaintenance: 'System maintenance scheduled for tomorrow.',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    applications: 'आवेदन',
    meritList: 'मेरिट सूची',
    cutoffPrediction: 'कट-ऑफ भविष्यवाणी',
    seatAllocation: 'सीट आवंटन',
    payments: 'भुगतान',
    exams: 'प्रवेश परीक्षा',
    mockTests: 'मॉक टेस्ट',
    documents: 'दस्तावेज़ केंद्र',
    settings: 'सेटिंग्स',
    logout: 'लॉगआउट',
    engineeringAdmissionsPortal: 'इंजीनियरिंग प्रवेश पोर्टल',
    searchPrograms: 'इंजीनियरिंग कार्यक्रम खोजें...',
    notifications: 'सूचनाएं',
    studentProfile: 'छात्र प्रोफ़ाइल',
    editSettings: 'खाता सेटिंग्स संपादित करें',
    myApplications: 'मेरे आवेदन',
    logoutSession: 'लॉगआउट / सत्र रीसेट',
    recentApplications: 'हाल के इंजीनियरिंग आवेदन',
    startApplication: 'नया इंजीनियरिंग आवेदन शुरू करें',
    draftApplication: 'इंजीनियरिंग आवेदन ड्राफ्ट करें',
    cancel: 'रद्द करें',
    submit: 'आवेदन जमा करें',
    studentName: 'छात्र का नाम',
    email: 'ईमेल',
    program: 'इंजीनियरिंग कार्यक्रम',
    department: 'विभाग',
    class12Marks: 'कक्षा 12 अंक (%)',
    jeeComedkScore: 'JEE/COMEDK स्कोर (%)',
    coursePreferences: 'कोर्स प्राथमिकताएं (वैकल्पिक)',
    addPreference: '+ प्राथमिकता जोड़ें',
    applicationId: 'आवेदन ID',
    academicMarks: 'शैक्षणिक अंक',
    examScore: 'परीक्षा स्कोर',
    totalScore: 'कुल स्कोर',
    paymentStatus: 'भुगतान स्थिति',
    status: 'स्थिति',
    actions: 'क्रियाएं',
    view: 'देखें',
    pay: 'भुगतान करें',
    paid: 'भुगतान हो गया',
    pending: 'लंबित',
    failed: 'विफल',
    underReview: 'समीक्षा में',
    admitted: 'प्रवेश मिला',
    processing: 'प्रसंस्करण में',
    jeeQualified: 'JEE योग्य',
    // Rural features
    ruralSupport: 'ग्रामीण सहायता',
    scholarships: 'छात्रवृत्ति',
    helplines: 'हेल्पलाइन',
    coachingCenters: 'कोचिंग केंद्र',
    transportation: 'परिवहन मार्गदर्शिका',
    communityForum: 'समुदाय मंच',
    computerLiteracy: 'कंप्यूटर साक्षरता',
    offlineForms: 'ऑफलाइन फॉर्म',
    downloadForm: 'आवेदन फॉर्म डाउनलोड करें',
    smsNotifications: 'एसएमएस सूचनाएं',
    language: 'भाषा',
    english: 'English',
    hindi: 'हिंदी',
    selectLanguage: 'भाषा चुनें',
    ruralFriendlyMode: 'ग्रामीण अनुकूल मोड',
    largeText: 'बड़ी टेक्स्ट',
    voiceGuidance: 'वॉइस मार्गदर्शन',
    // New features
    applyJee: 'JEE Main के लिए आवेदन करें',
    applyComedk: 'COMEDK के लिए आवेदन करें',
    gatewayToPrograms: 'JEE Main और COMEDK के माध्यम से शीर्ष इंजीनियरिंग कार्यक्रमों का आपका प्रवेश द्वार',
    applyForPrograms: 'JEE Main और COMEDK के माध्यम से इंजीनियरिंग कार्यक्रमों के लिए आवेदन करें',
    engineeringApplications: 'इंजीनियरिंग आवेदन',
    upcomingExams: 'आगामी परीक्षाएं',
    jeeRegistrationClosing: 'JEE Main पंजीकरण जल्दी बंद हो रहा है!',
    applicationUnderReview: 'आपका इंजीनियरिंग आवेदन समीक्षा में है।',
    systemMaintenance: 'सिस्टम रखरखाव कल निर्धारित है।',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};